### ISSUE TITLE
add_subdirectory(ink-stroke-modeler)

### ISSUE THREAD

**Issue by iflyyun** [google/ink-stroke-modeler#64]
The target name "ink_stroke_modeler_matrix)" is reserved or not valid for
  certain CMake features, such as generator expressions, and may result in
  undefined behavior.

**Comment by sfreilich** [comment]
Wait, what do you mean? I'm confused. Is the issue a stray  paren? Or is that a typo and something else makes the name invalid?

**Comment by sfreilich** [comment]
Fixed in https://github.com/google/ink-stroke-modeler/commit/d4eea943169de05a31cc095a39162d8d9b695a0f
